[package]
name = "chromatic"
version = "0.0.0"
edition = "2024"
description = "A small utility library for building and sampling colour maps."
license = "MIT"

[dependencies]
# num-traits = "0.2.19"
palette = "0.7.6"
thiserror = "2.0.12"
